# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AtuhtorDetail',
            new_name='AuthorDetail',
        ),
        migrations.RenameModel(
            old_name='Pbulisher',
            new_name='Publisher',
        ),
    ]
